version: "3"

services:
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Amstedam
      - USER=banana
      - PASS=banana
      - TRANSMISSION_WEB_HOME=/combustion-release/
    volumes:
      - ./config/transmission:/config
      - ./downloads:/downloads
    ports:
      - 9090:9091 
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Amstedam
    volumes:
      - ./config:/config
    depends_on:
      - transmission
    ports:
      - 9091:9117
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Amsterdam
    volumes:
      - ./config/radarr:/config
    depends_on:
      - jackett
    ports:
      - 9092:7878
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Amsterdam
    volumes:
      - ./config/sonarr:/config
    depends_on:
      - jackett
    ports:
      - 9093:8989
    restart: unless-stopped

  portainer:
    container_name: portainer
    ports:
      - 9094:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer:/data
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Amsterdam
    image: portainer/portainer
    restart: unless-stopped


networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24

